public.ls_homepage:
    route: '/'
    type: get
    controller: 'CoreController'
    methode: 'home'

public.ls_inscription:
    route: '/inscription'
    type: get
    controller: 'CoreController'
    methode: 'inscription'

public.ls_execute_inscription:
    route: '/inscription'
    type: post
    controller: 'CoreController'
    methode: 'executeInscription'

public.ls_connexion:
    route: '/connexion'
    type: get
    controller: 'CoreController'
    methode: 'connexion'

public.ls_execute_connexion:
    route: '/connexion'
    type: post
    controller: 'CoreController'
    methode: 'executeConnexion'

public.ls_deconnexion:
    route: '/deconnexion'
    type: get
    controller: 'CoreController'
    methode: 'deconnexion'

public.ls_voir_produit:
    route: '/produit-:idProduit'
    type: get
    controller: 'CoreController'
    methode: 'voirProduit'

admin.ls_homepage:
    route: '/administration/'
    type: get
    controller: 'CoreController'
    methode: 'adminHome'