public.lk_homepage:
    route: '/'
    type: get
    controller: 'myController'
    methode: 'home'

public.lk_contact:
    route: '/contact'
    type: post
    controller: 'myController'
    methode: 'contact'

public.lk_test:
    route: '/test/:id'
    type: get
    controller: 'myController'
    methode: 'test'

public.lk_test2:
    route: '/test/:id/ok'
    type: get
    controller: 'myController'
    methode: 'test2'
